version: "2.1"
services:
  microservices:
    build: .
    image: crudgochi
    ports:
      - '8086:8086'
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
  db:
    image: mysql
    container_name: sqldb

    environment:
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_DATABASE=crudexpenses'
    ports:
      - '3306:3306'
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10